### ISSUE TITLE
Enhancement request- other non-AWS S3 endpoints

### ISSUE THREAD

**Issue by acepelon** [jvsteiner/s3-image-uploader#1]
As the subject says, it would be great for my use case to support non-AWS s3-compatible endpoints.  

Thanks!
ACE

**Comment by jvsteiner** [comment]
Do you have a specific type of endpoint you are looking for?  Which cloud provider?

**Comment by acepelon** [comment]
My company, Datacore (not to be confused with Dataview's new upcoming Datacore!) makes an s3-compatible product which is hosted on prem.  You can point s3 clients to our gateway directly.  I think there would be minimal code change in your plugin- basically just have a configurable endpoint URL (http or https) and S3 listening port.

**Comment by jvsteiner** [comment]
What do you mean by S3 listening port?

**Comment by acepelon** [comment]
The TCP port that the endpoint is listening on for incoming S3 requests.  With AWS S3, it is listening on port 443 for https requests for example:
https://docs.aws.amazon.com/general/latest/gr/s3.html

**Comment by jvsteiner** [comment]
I'd be happy to do this, but can you give me a few examples of non-AWS s3-compatible endpoints that illustrate the different possibilities you'd like to be able to have support for?

**Comment by acepelon** [comment]
Confirmed, it is just the endpoint that is different- or should be, at least, assuming the vendors are s3-compliant.

https://geekflare.com/self-hosted-s3/ is an older article but likely valid enough.

**Comment by jvsteiner** [comment]
I'm happy to make changes - but I'd like the examples I asked for.  In case you'd prefer to submit a PR, I'd be happy to accept that as an alternative.  But I will need one or the other.  I wont doing a research project on top of a feature request - hope you understand:  this is a minor side project for me...

**Comment by acepelon** [comment]
I apologize, I didn't mean to add any consternation.  I thought you were asking for vendors that offered s3-compliant endpoints who aren't AWS.

If I better understand your question, maybe this is what you are asking for. Here's an rclone config showing an endpoint configured that terminates on one of my company's s3-compatible gateways (in my lab), where "1-domain-for-versioning" in the example is the domain (resolves in my own DNS) and 8090 is the TCP port on our gateway that is listening for incoming s3 requests:

> cat .config/rclone/rclone.conf

```
[1-domain-for-versioning]
type = s3
provider = Other
env_auth = true
access_key_id = ************
secret_access_key = secretkey
endpoint = http://1-domain-for-versioning:8090
```
where rclone lsd looks like:
```
[root@ace-scs-1 ~]# rclone lsd 1-domain-for-versioning:
          -1 2023-01-05 17:17:48        -1 bucket-for-versioning
          -1 2023-01-17 20:43:34        -1 warp-30000-objs-2023-0117-2043-33
          -1 2023-01-17 22:31:52        -1 warp-31000-objs-2023-0117-2231-51
          -1 2023-01-17 18:32:39        -1 warp-put-10005-objs-2023-0117-1832-36
          -1 2023-01-16 22:23:16        -1 warp-put-2023-0116-2223-15
          -1 2023-01-17 10:12:03        -1 warp-put-2023-0117-1012-02
          -1 2023-01-19 01:06:37        -1 warp-retention-100000-objs-2023-0119-0106-37
          -1 2023-02-06 16:21:35        -1 warp-retention-100000-objs-2023-0206-1621-34
          -1 2023-01-26 11:19:19        -1 warp-retention-5000-objs-2023-0126-1119-18
```

Or s3cmd's .s3cfg for the same setup looks like:
```
[default]
access_key = ************
secret_key = secretkey
host_base = 1-domain-for-versioning:8090
signature_v2 = True
check_ssl_certificate = False
use_https = False
multipart_chunk_size_mb = 100
```

If the above is not helpful, no worries.  I certainly don't want to waste your time.  Thanks!

**Comment by jvsteiner** [comment]
I planned to eventually add other non-AWS support, such as google or Azure, but support for non-AWS s3 compliant options was not something I had thought much about.  I'll leave this open, as I may end up doing it, but I'm not sure when.
