### ISSUE TITLE
A better UX Google PDF Viewer

### ISSUE THREAD

**Issue by MahmadSharaf** [jvsteiner/s3-image-uploader#14]
I found that it is possible to preview the PDF in a less cluttered way using Google's PDF viewer. It is exactly as your current approach but add `?embedded=true`.

```html
<iframe frameborder=0 border=0 width=100% height=480
src="https://docs.google.com/viewer?embedded=true&url={Document}">
</iframe>
```
- Current approach:
![image](https://github.com/jvsteiner/s3-image-uploader/assets/36701447/56cb3409-7670-4862-8bc6-d82b3495369f)

- Suggested approach
![image](https://github.com/jvsteiner/s3-image-uploader/assets/36701447/8ca8c9a3-41ea-495f-b445-7a0be5769516)

**Comment by jvsteiner** [comment]
I would be happy to review a PR

**Comment by MahmadSharaf** [comment]
And I would love to, really. Do you have a guideline that I need to follow, as I am not expert in such things but don't mind getting into it?

**Comment by jvsteiner** [comment]
do you have an example of how the "embedded" version looks in a live web page that you could share?  could be any pdf in any context...  just so I can play around without compiling everything

**Comment by MahmadSharaf** [comment]
The normal view: https://docs.google.com/viewer?embedded=true&url=https://www.africau.edu/images/default/sample.pdf?raw=true

![image](https://github.com/jvsteiner/s3-image-uploader/assets/36701447/bb9219bb-65b0-46fe-9117-b6b6936713a5)

The embedded view: https://docs.google.com/viewer?embedded=true&url=https://www.africau.edu/images/default/sample.pdf?raw=true

![image](https://github.com/jvsteiner/s3-image-uploader/assets/36701447/ebbfb738-de68-4425-b6a7-fb250b8cd778)

**Comment by jvsteiner** [comment]
I don't know, I am torn.  I like the cleaner style, but it seems like the embedded version lacks some buttons and widgets that might come in handy.  It's hard for me accept this as is - if you can make using this into a global option, I'll accept it.

**Comment by MahmadSharaf** [comment]
If you are referring to the print button and the one next to it, they are not working any way, at least for me. The sign-in button works, but don't see it as a feature, as it doesn't provide any significant advantage to be signed in at this very specific moment.

**Comment by jvsteiner** [comment]
hmm.  in my installation, I have zoom in/out buttons, a page turner/jumper, and a sidebar toggle too:

<img width="755" alt="image" src="https://github.com/jvsteiner/s3-image-uploader/assets/1165328/56a3231b-57c6-43b1-8f05-89e23274a959">

**Comment by MahmadSharaf** [comment]
Is this Google's PDF viewer using this url https://docs.google.com/viewer?embedded=true&url=https://www.africau.edu/images/default/sample.pdf?raw=true ?

It is totally different than mine, check the screenshot in my previous comment.

I love this orientation of buttons, I even don't have the sidebar. could you share more details about your system and which exact url and on what browser?

**Comment by jvsteiner** [comment]
ugh - I am an idiot.  This screenshot is from an embedded link that was created by a different plugin - not mine.  I actually dont use it much for pdfs myself - it was a feature someone asked for once.  ok, this looks ok for me as an idea - I'll get around to addin it

**Comment by jvsteiner** [comment]
merged
