### ISSUE TITLE
Security Risk with AWS Key and Secrets and Git

### ISSUE THREAD

**Issue by ajay-bhargava** [jvsteiner/s3-image-uploader#17]
Hi, 

For those of us who sync our repositories with Git, the addition of `data.json` to the `.obsidian/` folder creates a security risk as the AWS KEY and AWS SECRET are stored in plaintext. Would there be a way to have the plugin refer to the system AWS credentials during plugin load? 

I'm not familiar with how Plugins are loaded in Obsidian but a common way to include AWS credentials in JS is: 

```javascript
const AWS = require('aws-sdk');

// Create an AWS SDK client
const s3 = new AWS.S3();

// Get the AWS credentials from the environment
const credentials = new AWS.Credentials({
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
});

// Set the AWS credentials on the S3 client
s3.config.credentials = credentials;
```

Thanks!

**Comment by ajay-bhargava** [comment]
A janky workaround would simply be to: 

```bash
echo ".obsidian/plugins/s3-image-uploader/data.json" >> .gitignore
```

**Comment by jvsteiner** [comment]
I think syncing the `.obsidian` folder is generally not recommended.  I am also not sure it should be the plugins responsibility to ensure you don't publish your private data somewhere.  Folk don't typically publish their `.zshrc` file in a public repo either, probably for similar reasons, if not also others. Using system credentials would be a nice way to do it, but that is not platform independent, afaik, which would make that suggestion difficult.  While it's probably beyond the scope of what I was trying to achieve, if such an improvement was offered in a PR, I would certainly be inclined to include it.

**Comment by ajay-bhargava** [comment]
Happy to attempt a PR! Do you have guidance on how this plugin is loaded into Obsidian?

**Comment by jvsteiner** [comment]
how loaded?  same as the others I guess.  If you have not looked into it, I suggest the https://github.com/obsidianmd/obsidian-sample-plugin as a resource.

**Comment by jvsteiner** [comment]
closing due to age
