### ISSUE TITLE
Uploading on iOS version

### ISSUE THREAD

**Issue by SystemZ** [jvsteiner/s3-image-uploader#19]
Hi, on desktop this plugin work great!
I tried it on iOS 17.3.1 and I can't get it to work.
Similar to https://github.com/jvsteiner/s3-image-uploader/issues/9
I can record video to show my exact steps.

I used three methods:

### Share option from Apple Photos app.
In this case I see dialog like on screenshot below. Selecting import to vault just adds attachment, doesn't trigger plugin. I shared photo which is in heic format with Live Photo if it changes things 🤔
![image](https://github.com/jvsteiner/s3-image-uploader/assets/1836094/95552b12-dd01-421a-944c-2cc23df6149a)

### Copy photo from Apple Photos app

Same as before but in share dialog I selected "Copy photo".
Pasting it in note does nothing. I mean it's no op, nothing happens or there is no indication. Same as I would be using empty clipboard I guess.

### Attaching photo from obsidian 

I used attachment icon on Obsidian toolbar and selected same photo as in two previous examples.
It attaches like without plugin, photo goes to attachment folder like in first variant I described.
I also tried attaching not from photo library but png from files dialog, same result.

**Comment by hzj629206** [comment]
Hi @jvsteiner , I like this plugin and unfortunately it doesn't work on iOS (Maybe Android as well).

**obsidian-imgur-plugin** had the same issue: https://github.com/gavvvr/obsidian-imgur-plugin/issues/13
And eventually it supports mobile version.

Here is how to debug on mobile platform: https://github.com/gavvvr/obsidian-imgur-plugin/issues/13#issuecomment-1751957417

Here is the major code changes: https://github.com/gavvvr/obsidian-imgur-plugin/commit/72db49b76ee2395358ce04f85566ca2bfbeed096#diff-5f16ac40b8ca7280fd3a3032abe2076856616ec425af2945f1e4fe04c71009b5

Do you think it's possible to support mobile version just refer to the implementation of **obsidian-imgur-plugin**?
