### ISSUE TITLE
Concurrent uploads

### ISSUE THREAD

**Issue by iammatthias** [jvsteiner/s3-image-uploader#20]
Currently if you want to add multiple images they need to be attached individually. Is it possible drag-and-drop multiple images, or a folder?

**Comment by jvsteiner** [comment]
Currently only individually is supported.  I don't have a need for multiple upload in my use case, so I won't write support for it, but if you have an idea on how it should work, I will review a PR.

**Comment by iammatthias** [comment]
PR opened #21

**Comment by jvsteiner** [comment]
sorry, been travelling - will get to this next week

**Comment by jvsteiner** [comment]
Have merged, but it doesnt seem to be working properly.  I dragged two files in, but only the first gets uploaded

**Comment by jvsteiner** [comment]
never mind, I figured what I was doing wrong
