### ISSUE TITLE
Concurrent uploads doesn't respect `localUploadFolder` YAML

### ISSUE THREAD

**Issue by MahmadSharaf** [jvsteiner/s3-image-uploader#22]
The newly added concurrency feature is an amazing one, but I noticed that the files are uploaded to the location stated in the settings, not the one stated in YAML `localUploadFolder`

**Comment by jvsteiner** [comment]
@iammatthias would you be willing to take a crack at this?

**Comment by iammatthias** [comment]
@jvsteiner happy to take a look. My work schedule is a bit hectic right now, but I'll try to get to it before EoW.

**Comment by jvsteiner** [comment]
totally not urgent - thank you, once again, for your contribution

**Comment by jvsteiner** [comment]
done

**Comment by iammatthias** [comment]
Sorry, I've been caught up in some work. Glad this was resolved.

**Comment by jvsteiner** [comment]
no worries, thanks for your contribution.
