### ISSUE TITLE
Specifying S3 upload folder per note not working

### ISSUE THREAD

**Issue by MahmadSharaf** [jvsteiner/s3-image-uploader#27]
Hello there again,

This plugin streamlines my workflow and I cannot emphasize enough how awesome it is.

One particular functionality, so crucial for me that I cannot work without, has been failing. Although I fixed it at my side, I wanted to help as well.

Since the last release, the functionality for setting an S3 upload folder per note is not working any more. I found the problem to be in the below piece of code

```js
let folder = "";
if (localUpload) {
  folder = (_a2 = fm == null ? void 0 : fm.folder) != null ? _a2 : this.settings.localUploadFolder;
} else {
  folder = (_b2 = fm == null ? void 0 : fm.folder) != null ? _b2 : this.settings.folder;
}
```
My understanding is that code has the logic for two functionalities at the same time:
1. Whether to save media locally in the vault.
   - If settings flag `localUpload` is set to `True`, this means that the user wants the plugin to save all media files locally in the vault.
   - Then it checks where to save the folder locally,
      - If the note's frontmatter property `folder` exists or has a value. Then save it there.
      - If it is empty, then check for the settings value `localUploadFolder`.
2. Or upload it remotely on S3
   - If flag `localUpload` is set to `False`, this means that the user wants the plugin to upload all media to S3.
   - Then it checks where to upload the folder on S3.
      - If the note's frontmatter property `folder` exists or has a value. Then upload to it there
      - If not, then upload to the location specified in setting value `folder`.

Where it fails?
1. Frontmatter property `folder` is not stated anywhere in the settings, or what its functionality is.
2. Frontmatter Boolean property `uploadLocal` is hinted in Settings page. So that to be used to override whether to save the media locally or not, but it is not used in the code at all.
3. Frontmatter property `uploadFolder` is hinted in Settings page. So that to be used to specify where to save the media locally, but it is not used in the code at all.
4. It is not possible to specify S3 upload folder.

I believe the code could be altered as below to fix the problems

```js
let folder = "";
if (localUpload || fm.uploadLocal) {
  folder = (_a2 = fm == null ? void 0 : fm.uploadFolder) != null ? _a2 : this.settings.localUploadFolder;
} else {
  folder = (_b2 = fm == null ? void 0 : fm.localUploadFolder) != null ? _b2 : this.settings.folder;
}
```

If that works, it is worth mentioning the frontmatter property that specifies S3 upload folder per note in the settings, or where you see best fit.

**Comment by jvsteiner** [comment]
I certainly value your input and help, and I am very happy you are getting good use out of this plugin.  Could you please provide a PR for me to review?  I would be very happy to verify the behavior you describe and merge it.

**Comment by jvsteiner** [comment]
This is great, but is there an, er, less magical way to write it?  the compiler doesn't appreciate _a2 and _b2, and its not clear to me what it does.  Also, the nested ternary operations are quite hard to read.  regular if's might be better, even if it would use more space or be microscopically slower.

**Comment by jvsteiner** [comment]
I suspect you were inspecting the compiled/optimized version of the code instead of the source.  The source lines are:
```
if (localUpload) {
	folder = fm?.folder ?? this.settings.localUploadFolder;
} else {
	folder = fm?.folder ?? this.settings.folder;
}
```

**Comment by MahmadSharaf** [comment]
Yes, I definitely was.

In that case, excuse my ignorance, but I have to ask, how could I test the source code in Obsidian before submitting the PR?

**Comment by jvsteiner** [comment]
you would have to build it using `npm run build` and then arrange for the resulting `main.js` artifact to replace the one in the `.obsidian/plugins/s3-image-uploader/main.js` file within your vault.  Then you have to reload the plugin.  In my case, I make this process easier by keeping the actual git repository under the `.obsidian/plugins/s3-image-uploader` folder, and I also use another plugin, called https://github.com/pjeby/hot-reload to make this process less painful.  So, my workflow is:
1) pull up vscode for `.obsidian/plugins/s3-image-uploader`
2) make changes to the code
3) `npm run build`
4) hot reload does its thing
5) test changes

**Comment by jvsteiner** [comment]
I took another look at this.  I think its actually really simple.  I created a branch `localUpload` for you to test out - could you tell me if it meets your needs?

**Comment by MahmadSharaf** [comment]
Thank you for sharing the detailed steps on how to test the plugin. I have always wondered how to test Obsidian community plugins.

Sorry for not replying earlier, I have been caught in multiple things.

I have looked for the branch [here](https://github.com/jvsteiner/s3-image-uploader/branches/all), but I only found the master branch.

**Comment by jvsteiner** [comment]
I forgot to push it, sorry, please try again?

**Comment by jvsteiner** [comment]
also - forgot to mention.  the first time you go into the plugin project directory - after `cd s3-image-uploader` you will need to install dependencies: `npm install`.  I am assuming you have node installed, etc.  This step might need to be repeated, if the projects dependancies change.

**Comment by MahmadSharaf** [comment]
I tested, and it worked as expected, but with only concern. It is not possible to save a file locally on a per-note basis. Property `uploadLocal` is not utilized.

I achieved this, by modifying the condition for uploading to S3 from `if (!localUpload)` to `if (!(localUpload || fm?.uploadLocal))`:

```ts
if (!(localUpload || fm?.uploadLocal)) {
await this.s3.send(
	new PutObjectCommand({
		Bucket: this.settings.bucket,
		Key: key,
		Body: new Uint8Array(buf),
		ContentType: file.type,
	})
);
url = this.settings.imageUrlPath + key;
} else {
await this.app.vault.adapter.writeBinary(
	key,
	new Uint8Array(buf)
);
url =
	this.app.vault.adapter instanceof FileSystemAdapter
		? this.app.vault.adapter.getFilePath(key)
		: key;
}
```

Other than that, there are nice to have features:
1. Given that the plugin configured for local save (not S3 upload), allow the plugin to create the folder if it doesn't exist, instead of throwing an error. 
2. The Property for setting the folder for local save is the same as setting the folder for remote upload, which is `uploadLocal`. I am fine with it, but my concern is that it used to be `localUploadFolder`. So it might be a breaking change for some users.

**Comment by jvsteiner** [comment]
take a look at main.ts:115:

```
const localUpload = fm?.localUpload ?? this.settings.localUpload;
```

The frontmatter tag should be `localUpload`  not `uploadLocal`  like in your code.  Try that in the frontmatter, and see if my commit doesn't work as expected.  line 115 is designed to use whatever is in the frontmatter tag, if its present, and if not, then the settings, (where the default is false).

**Comment by MahmadSharaf** [comment]
Yes, it worked. In that case, we need to fix it in the settings descriptions.
![image](https://github.com/jvsteiner/s3-image-uploader/assets/36701447/4a0ce04e-3dec-4d48-bee5-8985629272b0)

**Comment by jvsteiner** [comment]
You are right. I will fix it and make a release later today On May 19, 2024, at 14:25, MahmadSharaf ***@***.***> wrote:﻿
Yes, it worked. In that case, we need to fix it in the settings descriptions.
image.png (view on web)
