### ISSUE TITLE
PR to add query params to the final url that is generated however, tag and master...

### ISSUE THREAD

**Issue by ObjectiveTruth** [jvsteiner/s3-image-uploader#32]
Hey there, I forked and added the ability to set query params (key, value) to the end of the final url. Everything works on my side and I'd like to merge back into your repo, however I noticed master has moved quite a bit beyond 0.2.13 (which is the latest version in Obsidian afaik).

If you want to eithr pull my branch below into a new branch on your repo and tag it 0.2.14, you can push that updated out to Obsidian so you don't mess any work that you're doing

https://github.com/ObjectiveTruth/s3-image-uploader/tree/feature/added_option_query_params

**Comment by jvsteiner** [comment]
Sure - thanks for your contribution, I will take a look.  Glad to hear the plugin is useful to you.

**Comment by jvsteiner** [comment]
resolved
