### ISSUE TITLE
minio cant access

### ISSUE THREAD

**Issue by wangyunsi** [jvsteiner/s3-image-uploader#5]
My minio s3 endpoint urls is https://abc.myhost.com instead of  https://s3.myhost.com.
its must be s3?
abc is not work.

**Comment by jvsteiner** [comment]
not supported yet, you are the first one to request it.  I haven't done it yet because I personally don't have a non-s3 provider to develop and test against, but I will put it in the backlog

**Comment by wangyunsi** [comment]
> https://github.com/jvsteiner/s3-image-uploader/pull/3

There is a pull request about non-AWS s3,This may had solved this problem, but it is not work for me to use Minio's S3 settings.

**Comment by jvsteiner** [comment]
You are right - I was just remembering that I already accepted such a PR.  What is the error or problem that you are experiencing?  I will need some more detailed information.

**Comment by wangyunsi** [comment]
I have set it,but its not work,the follows is my set.
![](https://abc.210814.xyz:19000/180805/2023/04/570b9489f75a804a731550d54ffc6944.png)
![](https://abc.210814.xyz:19000/180805/2023/04/570b9489f75a804a731550d54ffc6944.png)
when I  pasted a picture to the obsidian,the plug-in not work.

**Comment by jvsteiner** [comment]
is the plugin enabled?  What does the javascript console say?  you should paste any errors you find there

**Comment by wangyunsi** [comment]
Plugin enabled,
![](https://abc.210814.xyz:19000/180805/2023/04/0be5ef062649e896f474f7bda51e6c92.png)

**Comment by wangyunsi** [comment]
![](https://abc.210814.xyz:19000/180805/2023/04/8d383487c915eefe33874bf1c44674ab.png)

**Comment by jvsteiner** [comment]
It says that the region is missing - that is part of the S3 api, which minio should be compatible with, but the error says you didnt enter it.  Maybe you need to enter your region for minio.

**Comment by wangyunsi** [comment]
I add the region,there still have error
![](https://abc.210814.xyz:19000/180805/2023/04/930c381a058a712af0255072a9f299ef.png)

**Comment by wangyunsi** [comment]
I confirm that the key I  type in is right.
its work on Picgo

**Comment by wangyunsi** [comment]
![](https://abc.210814.xyz:19000/180805/2023/04/2810bb82e0eda7e5cb6140de02328208.png)

It can work on Picgo

**Comment by wangyunsi** [comment]
I have created a testing account:The minio is build on Synology docker
adminurl:https://abc.210814.xyz:19001/
user:s3test
password:s3tests3test

**Comment by jvsteiner** [comment]
What about the region?

**Comment by wangyunsi** [comment]
us-north-1

**Comment by jvsteiner** [comment]
but did you put it in the settings?

**Comment by wangyunsi** [comment]
yes,I have send you a test account.You can make a try.

**Comment by jvsteiner** [comment]
what bucket?

**Comment by wangyunsi** [comment]
This is Minio Backend management
You can fnd any information you want abou S3-api
visit:https://abc.210814.xyz:19001/
user:s3test
password:s3tests3test

S3 date url is https://abc.210814.xyz:19000

**Comment by jvsteiner** [comment]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/1165328/235084777-93e732cf-2ef4-4291-9766-028f6cfad2a1.png">

can you set `Access-Control-Allow-Origin`  for the test bucket, please?

**Comment by wangyunsi** [comment]
ok

**Comment by wangyunsi** [comment]
I allready set the bucket to public. anyone will be able to upload, download and delete files from this Bucket

**Comment by jvsteiner** [comment]
It doesn't matter.  The bucket will allow it, but my browser wont make the request, because the `Access-Control-Allow-Origin`  is not set during the preflight check (OPTIONS) call.  The value of this header should be set to `*`.  I mentioned this in the README.

**Comment by jvsteiner** [comment]
access to the test bucket is removed, I am assuming you solved the problem?

**Comment by jvsteiner** [comment]
I made a release for a different issue (I think) worth trying to update before reporting back

**Comment by wangyunsi** [comment]
Im trying to solve this problem,To set the CORS policy for the bucket I rebuild the Minio service.

**Comment by wangyunsi** [comment]
I still not solve this problem.I had created an admin account for you to test it.

user:test
passwd:testtest

May be its the problem of Minio,I think!

[https://github.com/minio/minio/issues/11111](url)

**Comment by jvsteiner** [comment]
I'm going to leave this issue open for now, in case you get any additional information to help, however, as things stand now, I don't have time to do any more trouble shooting on your specific minio instance.

**Comment by wangyunsi** [comment]
I used Synology own reverse proxy server. I tried a lot, but it still not work. Even s3broswer it can connect to my own minio service. Although it did not solve the problem, thank you for your help.
At last,it still have error.
![](https://abc.210814.xyz:19000/test/2023/04/622e8fbc06e158d35e20a95bd369f08a.png)

**Comment by nicksmith53** [comment]
What is the error you are still getting?

I have been using minio without any issue, and also tested with the public [minio test server](https://min.io/docs/minio/linux/administration/minio-console.html#logging-in) using these settings:
```
  "accessKey": "Q3AM3UQ867SPQQA43P2F",
  "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
  "region": "us-east-1",
  "bucket": "bucket",
  "useCustomEndpoint": true,
  "customEndpoint": "https://play.min.io/",
  "forcePathStyle": true
```

**Comment by wangyunsi** [comment]
@nicksmith53 

The same error
![](https://raw.githubusercontent.com/wanghaihua/img/main/20230504164539.png)

This is my config

![](https://raw.githubusercontent.com/wanghaihua/img/main/20230504164834.png)
![](https://raw.githubusercontent.com/wanghaihua/img/main/20230504164857.png)

**Comment by wangyunsi** [comment]
@nicksmith53 
https://play.min.io:9443/     its not work
https://play.min.io/   its work

**Comment by wangyunsi** [comment]
Also backblaze.com S3 API got the same error.

**Comment by nicksmith53** [comment]
I'm not able to replicate this issue.
Checking the network tab of my obsidian debug console I see requests that do have the header in your error message:
![image](https://user-images.githubusercontent.com/1323556/236304771-db447118-e1ed-43b6-9033-7e8b9b4e7f0a.png)

Could there be another plugin that is interfeering? 
Can you create a new empty obsidian vault with only this s3-iamge plugin to test again?

**Comment by wangyunsi** [comment]
Set endpoint https://play.min.io,Its work!But my self build Minio on Synology,Still not work.
And,I try backblaze.com
B2 S3 api,I got the same error.
Can this plugin support backblaze B2?

**Comment by wangyunsi** [comment]
Thats will be great!

**Comment by jvsteiner** [comment]
made a new release.  you might have to restart obsidian after making the settings change

**Comment by wangyunsi** [comment]
> made a new release. you might have to restart obsidian after making the settings change

No cors error,but there got new error
![](https://abc.210814.xyz:19000/blog/2023/05/20230505213936.png)

**Comment by wangyunsi** [comment]
The error only appear on my self build Minio(on my Synology),And its work well on backblaze B2.Thank you for your work!
