### ISSUE TITLE
Support the access address of CDN

### ISSUE THREAD

**Issue by monlor** [jvsteiner/s3-image-uploader#6]

**Comment by jvsteiner** [comment]
can you be more specific?

**Comment by monlor** [comment]
For example, my entoint is s3.xxx.com, and the access address through the CDN is cdn.xxx.com, so I hope to automatically rewrite the access link to https://cdn.xxx.com instead of https://s3.xxxx .com/<bucket>

**Comment by monlor** [comment]
The plug -in work is very good, there is no error. What I mentioned is a feature. I want to be able to add a configuration general, rewrite the actual access address of the picture, the CDN access speed will be faster

**Comment by monlor** [comment]
Yes, ￼Hope to add this option, thank you

**Comment by jvsteiner** [comment]
I'm leaning towards not implementing this for now.  It's probably not a lot of work, however, it seems like a bit of an overkill.  Obsidian is a personal knowledge management program.  The links that are created here are for personal use.  A CDN is designed to give a worldwide audience fast access to the resources.  Using cloudfront vs. regular s3, for example, might shave a few milliseconds off the page load time but the single user is the only one who might notice.  I don't see the benefit.  

On the other hand, if you feel like implementing it, I'm happy to consider PR's.

If you have a specific use case or performance issue you are trying to address that would justify the additional expense and trouble of CDN hosting, please let me know.

**Comment by monlor** [comment]
Obidian can not only manage personal knowledge base, but also use it to write blogs. If you can put cdn's picture links, I can make it more convenient for everyone to visit after publishing the article.

**Comment by monlor** [comment]
I'm using typecho, and there are no relevant plug-ins now, so I can only copy it manually. I saw that there is a wordpress plug-in that can be released directly.

**Comment by jvsteiner** [comment]
playing devils advocate here, it sounds like it could be accomplished using find/replace, no?
