### ISSUE TITLE
Problems With Instructions 🫤🤯

### ISSUE THREAD

**Issue by jimparrillo** [jvsteiner/s3-image-uploader#7]
Hey there - 

I love the idea of using s3 for my images, but unfortunately, I don't have a PhD in coding. :/ I spent two hours just trying to figure out the policy and JSON and ended up giving up. I do know enough about coding to be dangerous, but don't deal with coding or s3 on a daily basis. There seems to be an assumption in a LOT of plugins that all users can quickly grasp these kinds of instructions and beep-bop-boop... it's so easy. Nothing can be further from the truth.

HOWEVER, I am a UX Designer and would be happy to help out on developing more detailed explanations and step-by-step instruction guide for people (like me) who don't know the intricacies of proper JSON syntax but can follow more detailed instructions. Let me know if you want some help on fleshing this out a bit more and making it a bit more understandable.

Thanks!

Jim

**Comment by jvsteiner** [comment]
Hey, thanks for taking a look at the project, I hope you get it set up ok.  The I'm happy to take a PR. The problem here is that AWS access policy stuff is inherently arcane.  This is not my fault, and it's outside the scope of what I am trying to achieve to try and explain it.   I say that with the utmost empathy for those who arriving at this for the first time.  If you go through this and work out how to do it, and would be wiling to document your experience for others, I'd be happy to include it in the README

**Comment by jvsteiner** [comment]
![screencapture-s3](https://github.com/jvsteiner/s3-image-uploader/assets/1165328/67f1c017-1e18-4088-bdfa-fe5ebbcbbac6)

This is what permissions is supposed to look like in the console for open access (to anyone, which is what my use case requires)

**Comment by jimparrillo** [comment]
Oh yeah - I TOTALLY understand how weird and wonky the Amazon Policy stuff is - so I don't fault you one bit. Thanks for the screenshot. I'll give it a try again. I think I didn't realize that the CORS is a *separate* part... because it's below the bucket policy (I thought they were the same thing)

I also routinely get confused with things like "<insert your file name>" or "'...insert-filename-here'"

Am I supposed to keep the "<>" am I supposed to keep the ellipsis? Am I supposed to keep the single quotes? There's no real standard and every system explains things differently. So when things go wrong, I assume that I f**ked something up.

I'll try it again and take some notes on how to document the process a little more explicitly. I could even put together a 'how to for non-technical people.'

**Comment by jvsteiner** [comment]
closing this for now
